# 命名：4m
# 説明：4m
# 説明：generated by Minecraft Particle Shape Generator
# 説明：points: 20
# >
# =/function neofunction:asset/particle/circle/item1767/4m

particle minecraft:sweep_attack ^4 ^0 ^0 0 0 0 0 1 force
particle minecraft:sweep_attack ^3.804 ^0 ^1.235 0 0 0 0 1 force
particle minecraft:sweep_attack ^3.237 ^0 ^2.35 0 0 0 0 1 force
particle minecraft:sweep_attack ^2.353 ^0 ^3.235 0 0 0 0 1 force
particle minecraft:sweep_attack ^1.238 ^0 ^3.803 0 0 0 0 1 force
particle minecraft:sweep_attack ^0.003 ^0 ^4 0 0 0 0 1 force
particle minecraft:sweep_attack ^-1.232 ^0 ^3.805 0 0 0 0 1 force
particle minecraft:sweep_attack ^-2.348 ^0 ^3.239 0 0 0 0 1 force
particle minecraft:sweep_attack ^-3.233 ^0 ^2.355 0 0 0 0 1 force
particle minecraft:sweep_attack ^-3.802 ^0 ^1.242 0 0 0 0 1 force
particle minecraft:sweep_attack ^-4 ^0 ^0.006 0 0 0 0 1 force
particle minecraft:sweep_attack ^-3.806 ^0 ^-1.229 0 0 0 0 1 force
particle minecraft:sweep_attack ^-3.241 ^0 ^-2.345 0 0 0 0 1 force
particle minecraft:sweep_attack ^-2.358 ^0 ^-3.231 0 0 0 0 1 force
particle minecraft:sweep_attack ^-1.245 ^0 ^-3.801 0 0 0 0 1 force
particle minecraft:sweep_attack ^-0.01 ^0 ^-4 0 0 0 0 1 force
particle minecraft:sweep_attack ^1.226 ^0 ^-3.807 0 0 0 0 1 force
particle minecraft:sweep_attack ^2.342 ^0 ^-3.242 0 0 0 0 1 force
particle minecraft:sweep_attack ^3.229 ^0 ^-2.36 0 0 0 0 1 force
particle minecraft:sweep_attack ^3.8 ^0 ^-1.248 0 0 0 0 1 force
