# 命名：horizontal2m5
# 説明：horizontal2m5
# 説明：generated by Minecraft Particle Shape Generator
# 説明：points: 16
# >
# =/function neofunction:asset/particle/circle/item1767/horizontal2m5

particle minecraft:sweep_attack ^2.5 ^0 ^0 0 0 0 0 1 normal
particle minecraft:sweep_attack ^2.445 ^0 ^0.52 0 0 0 0 1 normal
particle minecraft:sweep_attack ^2.284 ^0 ^1.016 0 0 0 0 1 normal
particle minecraft:sweep_attack ^2.023 ^0 ^1.469 0 0 0 0 1 normal
particle minecraft:sweep_attack ^1.674 ^0 ^1.857 0 0 0 0 1 normal
particle minecraft:sweep_attack ^1.251 ^0 ^2.164 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0.774 ^0 ^2.377 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0.263 ^0 ^2.486 0 0 0 0 1 normal
particle minecraft:sweep_attack ^-0.259 ^0 ^2.487 0 0 0 0 1 normal
particle minecraft:sweep_attack ^-0.77 ^0 ^2.378 0 0 0 0 1 normal
particle minecraft:sweep_attack ^-1.248 ^0 ^2.166 0 0 0 0 1 normal
particle minecraft:sweep_attack ^-1.671 ^0 ^1.86 0 0 0 0 1 normal
particle minecraft:sweep_attack ^-2.021 ^0 ^1.472 0 0 0 0 1 normal
particle minecraft:sweep_attack ^-2.282 ^0 ^1.02 0 0 0 0 1 normal
particle minecraft:sweep_attack ^-2.445 ^0 ^0.523 0 0 0 0 1 normal
particle minecraft:sweep_attack ^-2.5 ^0 ^0.004 0 0 0 0 1 normal

particle minecraft:cherry_leaves ^2.5 ^0 ^0 0 0 0 0 1 normal
particle minecraft:cherry_leaves ^2.284 ^0 ^1.016 0 0 0 0 1 normal
particle minecraft:cherry_leaves ^2.023 ^0 ^1.469 0 0 0 0 1 normal

particle minecraft:cherry_leaves ^1.251 ^0 ^2.164 0 0 0 0 1 normal
particle minecraft:cherry_leaves ^0.774 ^0 ^2.377 0 0 0 0 1 normal

particle minecraft:cherry_leaves ^-0.259 ^0 ^2.487 0 0 0 0 1 normal
particle minecraft:cherry_leaves ^-0.77 ^0 ^2.378 0 0 0 0 1 normal

particle minecraft:cherry_leaves ^-1.671 ^0 ^1.86 0 0 0 0 1 normal
particle minecraft:cherry_leaves ^-2.021 ^0 ^1.472 0 0 0 0 1 normal

particle minecraft:cherry_leaves ^-2.445 ^0 ^0.523 0 0 0 0 1 normal
particle minecraft:cherry_leaves ^-2.5 ^0 ^0.004 0 0 0 0 1 normal

particle minecraft:cloud ^2.5 ^0 ^0 0 0 0 0 1 normal
particle minecraft:cloud ^2.445 ^0 ^0.52 0 0 0 0 1 normal

particle minecraft:cloud ^2.023 ^0 ^1.469 0 0 0 0 1 normal
particle minecraft:cloud ^1.674 ^0 ^1.857 0 0 0 0 1 normal

particle minecraft:cloud ^0.774 ^0 ^2.377 0 0 0 0 1 normal
particle minecraft:cloud ^0.263 ^0 ^2.486 0 0 0 0 1 normal

particle minecraft:cloud ^-0.77 ^0 ^2.378 0 0 0 0 1 normal
particle minecraft:cloud ^-1.248 ^0 ^2.166 0 0 0 0 1 normal

particle minecraft:cloud ^-2.021 ^0 ^1.472 0 0 0 0 1 normal

particle minecraft:cloud ^-2.445 ^0 ^0.523 0 0 0 0 1 normal
particle minecraft:cloud ^-2.5 ^0 ^0.004 0 0 0 0 1 normal
