# 命名：verticalhalf5m
# 説明：varticlahalf5m
# 説明：generated by Minecraft Particle Shape Generator
# 説明：points: 21
# >
# =/function neofunction:asset/particle/circle/item1767/verticalhalf5m

particle minecraft:sweep_attack ^0 ^5 ^0 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^4.939 ^0.782 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^4.756 ^1.544 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^4.456 ^2.269 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^4.046 ^2.938 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^3.537 ^3.534 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^2.941 ^4.044 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^2.272 ^4.454 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^1.548 ^4.754 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^0.786 ^4.938 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^0.004 ^5 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-0.778 ^4.939 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-1.541 ^4.757 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-2.265 ^4.457 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-2.934 ^4.048 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-3.531 ^3.54 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-4.041 ^2.944 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-4.452 ^2.276 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-4.753 ^1.552 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-4.937 ^0.79 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-5 ^0.008 0 0 0 0 1 normal
