# 命名：verticalhalf3m
# 説明：varticlahalf3m
# 説明：generated by Minecraft Particle Shape Generator
# 説明：points: 21
# >
# =/function neofunction:asset/particle/circle/item1767/verticalhalf3m

particle minecraft:sweep_attack ^0 ^3 ^0 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^2.963 ^0.469 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^2.853 ^0.927 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^2.673 ^1.361 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^2.428 ^1.763 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^2.122 ^2.12 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^1.765 ^2.426 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^1.363 ^2.672 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^0.929 ^2.853 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^0.471 ^2.963 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^0.002 ^3 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-0.467 ^2.963 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-0.924 ^2.854 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-1.359 ^2.674 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-1.761 ^2.429 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-2.119 ^2.124 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-2.425 ^1.766 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-2.671 ^1.366 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-2.852 ^0.931 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-2.962 ^0.474 0 0 0 0 1 normal
particle minecraft:sweep_attack ^0 ^-3 ^0.005 0 0 0 0 1 normal
